<?php

namespace ContainerSeN2D7U;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SgeiuvgService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.Sgeiuvg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Sgeiuvg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'favoritesManager' => ['privates', 'App\\Service\\FavoritesManager', 'getFavoritesManagerService', true],
        ], [
            'favoritesManager' => 'App\\Service\\FavoritesManager',
        ]);
    }
}
