<?php

namespace ContainerSeN2D7U;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_K0jRdXService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.K0j_RdX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.K0j_RdX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'casting' => ['privates', '.errored..service_locator.K0j_RdX.App\\Entity\\Casting', NULL, 'Cannot autowire service ".service_locator.K0j_RdX": it references class "App\\Entity\\Casting" but no such service exists.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'casting' => 'App\\Entity\\Casting',
            'entityManager' => '?',
        ]);
    }
}
