<?php

namespace ContainerSeN2D7U;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCastingTypeService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Form\CastingType' shared autowired service.
     *
     * @return \App\Form\CastingType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/CastingType.php';

        return $container->privates['App\\Form\\CastingType'] = new \App\Form\CastingType();
    }
}
