<?php

namespace ContainerSeN2D7U;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFavoritesManagerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\FavoritesManager' shared autowired service.
     *
     * @return \App\Service\FavoritesManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/FavoritesManager.php';

        return $container->privates['App\\Service\\FavoritesManager'] = new \App\Service\FavoritesManager(($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ($container->privates['monolog.logger'] ?? $container->getMonolog_LoggerService()), $container->getEnv('bool:FAVORITES_EMPTY_ENABLED'));
    }
}
