<?php

namespace ContainerSeN2D7U;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGenreRepositoryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Repository\GenreRepository' shared autowired service.
     *
     * @return \App\Repository\GenreRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Repository/GenreRepository.php';

        return $container->privates['App\\Repository\\GenreRepository'] = new \App\Repository\GenreRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
