<?php

namespace ContainerSeN2D7U;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMovie5Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.zEkbIUL.App\Entity\Movie' shared service.
     *
     * @return \App\Entity\Movie
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.zEkbIUL": it references class "App\\Entity\\Movie" but no such service exists.');
    }
}
