<?php

namespace ContainerSeN2D7U;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOmdbApiService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\OmdbApi' shared autowired service.
     *
     * @return \App\Service\OmdbApi
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/OmdbApi.php';

        return $container->privates['App\\Service\\OmdbApi'] = new \App\Service\OmdbApi(($container->privates['.debug.http_client'] ?? $container->get_Debug_HttpClientService()), ($container->privates['parameter_bag'] ?? ($container->privates['parameter_bag'] = new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container))));
    }
}
