<?php

namespace ContainerSeN2D7U;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPersonRepositoryService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Repository\PersonRepository' shared autowired service.
     *
     * @return \App\Repository\PersonRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Repository/PersonRepository.php';

        return $container->privates['App\\Repository\\PersonRepository'] = new \App\Repository\PersonRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
