<?php

namespace ContainerSeN2D7U;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Firewall_Map_Config_ApiSecureService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'security.firewall.map.config.api_secure' shared service.
     *
     * @return \Symfony\Bundle\SecurityBundle\Security\FirewallConfig
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-bundle/Security/FirewallConfig.php';

        return $container->privates['security.firewall.map.config.api_secure'] = new \Symfony\Bundle\SecurityBundle\Security\FirewallConfig('api_secure', 'security.user_checker', '.security.request_matcher.TKYa7ds', true, true, 'security.user.provider.concrete.app_user_provider', NULL, 'security.authenticator.jwt.api_secure', NULL, NULL, [0 => 'jwt'], NULL);
    }
}
