<?php

namespace ContainerVFYgrAW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XLsihu8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XLsihu8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XLsihu8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'movieRepository' => ['privates', 'App\\Repository\\MovieRepository', 'getMovieRepositoryService', false],
        ], [
            'movieRepository' => 'App\\Repository\\MovieRepository',
        ]);
    }
}
