<?php

namespace ContainerVFYgrAW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WumxNdWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wumxNdW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wumxNdW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'castingRepository' => ['privates', 'App\\Repository\\CastingRepository', 'getCastingRepositoryService', true],
            'movie' => ['privates', '.errored..service_locator.wumxNdW.App\\Entity\\Movie', NULL, 'Cannot autowire service ".service_locator.wumxNdW": it references class "App\\Entity\\Movie" but no such service exists.'],
        ], [
            'castingRepository' => 'App\\Repository\\CastingRepository',
            'movie' => 'App\\Entity\\Movie',
        ]);
    }
}
