<?php

namespace ContainerVFYgrAW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZEkbIULService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zEkbIUL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zEkbIUL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'movie' => ['privates', '.errored..service_locator.zEkbIUL.App\\Entity\\Movie', NULL, 'Cannot autowire service ".service_locator.zEkbIUL": it references class "App\\Entity\\Movie" but no such service exists.'],
        ], [
            'doctrine' => '?',
            'movie' => 'App\\Entity\\Movie',
        ]);
    }
}
