<?php

namespace ContainerVFYgrAW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6HjDXbGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6HjDXbG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6HjDXbG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'favoritesManager' => ['privates', 'App\\Service\\FavoritesManager', 'getFavoritesManagerService', true],
            'movie' => ['privates', '.errored..service_locator.6HjDXbG.App\\Entity\\Movie', NULL, 'Cannot autowire service ".service_locator.6HjDXbG": it references class "App\\Entity\\Movie" but no such service exists.'],
        ], [
            'favoritesManager' => 'App\\Service\\FavoritesManager',
            'movie' => 'App\\Entity\\Movie',
        ]);
    }
}
