<?php

namespace ContainerVFYgrAW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Eyyzr_TService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eyyzr.t' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eyyzr.t'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'castingRepository' => ['privates', 'App\\Repository\\CastingRepository', 'getCastingRepositoryService', true],
            'movieRepository' => ['privates', 'App\\Repository\\MovieRepository', 'getMovieRepositoryService', false],
        ], [
            'castingRepository' => 'App\\Repository\\CastingRepository',
            'movieRepository' => 'App\\Repository\\MovieRepository',
        ]);
    }
}
