<?php

namespace ContainerVFYgrAW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Hrb6f6nService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hrb6f6n' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hrb6f6n'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'mySlugger' => ['privates', 'App\\Service\\MySlugger', 'getMySluggerService', true],
        ], [
            'entityManager' => '?',
            'mySlugger' => 'App\\Service\\MySlugger',
        ]);
    }
}
