<?php

namespace ContainerVFYgrAW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCastingService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.K0j_RdX.App\Entity\Casting' shared service.
     *
     * @return \App\Entity\Casting
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.K0j_RdX": it references class "App\\Entity\\Casting" but no such service exists.');
    }
}
