<?php

namespace ContainerVFYgrAW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMoviesSlugifyCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\MoviesSlugifyCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\MoviesSlugifyCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:movies:slugify', [], 'Slugifies movies titles in the database', false, function () use ($container): \App\Command\MoviesSlugifyCommand {
            return ($container->privates['App\\Command\\MoviesSlugifyCommand'] ?? $container->load('getMoviesSlugifyCommandService'));
        });
    }
}
