<?php

namespace ContainerVFYgrAW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMoviesSlugifyCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\MoviesSlugifyCommand' shared autowired service.
     *
     * @return \App\Command\MoviesSlugifyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/MoviesSlugifyCommand.php';

        $container->privates['App\\Command\\MoviesSlugifyCommand'] = $instance = new \App\Command\MoviesSlugifyCommand(($container->privates['App\\Repository\\MovieRepository'] ?? $container->getMovieRepositoryService()), ($container->privates['App\\Service\\MySlugger'] ?? $container->load('getMySluggerService')), ($container->services['doctrine'] ?? $container->getDoctrineService()));

        $instance->setName('app:movies:slugify');
        $instance->setDescription('Slugifies movies titles in the database');

        return $instance;
    }
}
