<?php

namespace ContainerVFYgrAW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMoviesPosterCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\MoviesPosterCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\MoviesPosterCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:movies:poster', [], 'Get movies posters from omdbapi.com', false, function () use ($container): \App\Command\MoviesPosterCommand {
            return ($container->privates['App\\Command\\MoviesPosterCommand'] ?? $container->load('getMoviesPosterCommandService'));
        });
    }
}
