<?php

namespace ContainerVFYgrAW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMoviesPosterCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\MoviesPosterCommand' shared autowired service.
     *
     * @return \App\Command\MoviesPosterCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/MoviesPosterCommand.php';
        include_once \dirname(__DIR__, 4).'/src/Service/OmdbApi.php';

        $container->privates['App\\Command\\MoviesPosterCommand'] = $instance = new \App\Command\MoviesPosterCommand(($container->privates['App\\Repository\\MovieRepository'] ?? $container->getMovieRepositoryService()), ($container->services['doctrine'] ?? $container->getDoctrineService()), new \App\Service\OmdbApi(($container->privates['.debug.http_client'] ?? $container->get_Debug_HttpClientService()), ($container->privates['parameter_bag'] ?? ($container->privates['parameter_bag'] = new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container)))));

        $instance->setName('app:movies:poster');
        $instance->setDescription('Get movies posters from omdbapi.com');

        return $instance;
    }
}
