<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVFYgrAW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVFYgrAW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVFYgrAW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVFYgrAW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVFYgrAW\App_KernelDevDebugContainer([
    'container.build_hash' => 'VFYgrAW',
    'container.build_id' => '7b8ecccc',
    'container.build_time' => 1680250929,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVFYgrAW');
